version: "3.8"

services:
  traefik:
    image: "traefik:v2.0.0"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure=true
      - --api.dashboard=true
      # - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.traefik.rule=Host(`dashboard.docker.localhost`)"
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/app
    ports:
      - "8081:8081"
    links:
      - mysql
    environment:
      - APP_URL=http://127.0.0.1:8080
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=wmc_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
    labels:
      - "traefik.http.routers.app.rule=Host(`wmc.docker.localhost`)"
        
  mysql:
    image: 'mysql:5.7'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wmc_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql

volumes:
  mysql-data:
